### ISSUE TITLE
Create a Helm Chart (or other deployment mechanism) to install the smi controller

### ISSUE THREAD

**Issue by keithmattix** [nicholasjackson/istio-smi-controller#4]
There doesn't appear to be a deployable form of the istio-smi-controller anywhere in this repo. This is a blocker for setting up the SMI Conformance GitHub action. We need to create a helm chart (or alternative artifact) for deploying this controller.

**Comment by keithmattix** [comment]
We also need to set up a github action to deploy new versions of the istio-smi-controller to Dockerhub

**Comment by nicholasjackson** [comment]
Hi Keith, the main SDK has a helm chart that you can use, you just need to
set the correct value for your own docker image.

smi-controller-sdk/helm/smi-controller at main ·
servicemeshinterface/smi-controller-sdk (github.com)
<https://github.com/servicemeshinterface/smi-controller-sdk/tree/main/helm/smi-controller>

image:
repository: nicholasjackson/smi-controller-example
pullPolicy: IfNotPresent

**Comment by keithmattix** [comment]
Am I good to just create a personal dockerhub repo for now? I was thinking of trying to get an image published to the [SMI Dockerhub Org](https://hub.docker.com/u/servicemeshinterface). If I need to, my personal account will work for now

**Comment by bridgetkromhout** [comment]
Closing due to project archival: https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/
